### PR TITLE
Add aws support

### PR DESCRIPTION
**Pull request by FMTV13**
Add 'carrierwave-aws' gem support.

### CODE REVIEW

**Comment by equivalent** [comment]
I'll release new version in next few days as I'm on holiday right now

**Comment by equivalent** [comment]
@FMTV13
    
FMTV13version 1.2.0 was released  today including your PR can you pls give me feedback if everything works as expected ? thx

**Comment by FMTV13** [comment]
@equivalent , everything works as expected. Thanks for new version ;)

**Comment by equivalent** [comment]
@FMTV13 no problem, thank you again for contributing

**Pull request merged**
